---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: items-api-secrets
  namespace: demo-dev
spec:
  encryptedData:
    API_KEY: AgCqJU6Xkj5NMX40No7VyeSpiGJtLqdQLLL12DMpX8V8RagZYnUdKhhz51UVGuNLsaofK146SlHOwVi1NovzPWnzhDQ2aHjkAMjn0gAYUKQs1DuY6FaZKfAhKMHg7STtrm2PYl/pk5A/AWmNCTNsfxK7ognGAioCoUBme4OhBqxX8zsRyW05jw0WeSWfjWHiM86nKc6wMvISQtnj1nMwreQ+a0Lhxy6fwFNQi3VR3oB1kPw5Q+vu95aSS2+nxaU7lS+97kYwtVvJ59kPZ1st6wXu4ge5Ny5SDr8JX8zoL/CgShWZKENESnLFAInFHZe1JaF/NFa17xlbUETKjWA95Sbc/3DY3xrUwrfVLj5G+TUbDEqwehAMLtCfaulZ/qeBz7V/r/Fvkn1TWAC5kSrobytdtv/9UFrX/ue8Y6ekYpey5BL1ZVFHPlOLEkIK90K0GNHmrCostLn/EsJpZcJnzn2S/jrPoULwPTOmimfbrljd7TTn3lvbzQxoig8l2DOL0Mf5HAFx4mZPbRXdhNNmo75fdqiQ62utwWWctasbOLgWq2jIFSoJ+uGn2AEEj+eGNxG3h4IMHaN6OWQFs9olPhuIcwnMXfFvVn9LyGfKoeFxFRS45Y7JXCqE5o++4Aw761Jks1x5fJItIv5FdlBmk1kuXZg8k5fqwlZwzfui/myemLsZy+HRA9J9ed7kOQzycD3O4SZs8Jhp4Auz
  template:
    metadata:
      name: items-api-secrets
      namespace: demo-dev
